# nixpacks.toml
[phases.setup]
# keep all auto-detected packages, plus pull in the GLib/GObject, Cairo, Pango, GDK-Pixbuf, libffi, & shared-mime libs
nixPkgs = [
  "...",
  "glib",
  "gobject-introspection",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "libffi",
  "shared-mime-info"
]
